### PR TITLE
DOCSP-31790 update title to alphabetize legacy product menu

### PR DESCRIPTION
**Pull request by sarahemlin**
Hey @jwilliams-mongo !

I'm renaming the title field in the snooty.toml files today so that DOP can set up the legacy menu to pull from that field.

Here's my[ build log ](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6539564e3ede3ec1110c5c8b)& [preview link](https://preview-mongodbsarahemlin.gatsbyjs.io/atlas-cli/DOCSP-31790/). 

[JIRA link](https://jira.mongodb.org/browse/DOCSP-31790)

Thanks for your review & merge!
Sarah

### CODE REVIEW

**Review by jwilliams-mongo — APPROVED** [review]
@sarahemlin LGTM

**Comment by jwilliams-mongo** [comment]
@sarahemlin do you know if this needs to be backported to earlier versions?

**Comment by sarahemlin** [comment]
@jwilliams-mongo, yes, we probably need to backport if this applies only to one version.  It's the EOL'd versions that would need it the most.  Thank you for thinking of that.  Is backporting too complex for me, and I should just ask for it on my other tickets from the get-go?

**Comment by jwilliams-mongo** [comment]
I've asked Corry to send you a wiki page if we have one that describes backporting. If you don't feel comfortable doing that we can help you here

**Pull request merged**
