### PR TITLE
(DOCSP-43546) Release notes for 1.27.1

### PR DESCRIPTION
**Pull request by sarahsimpers**
- [DOCSP](https://jira.mongodb.org/browse/DOCSP-43546)
- [STAGING](https://deploy-preview-643--docs-atlas-cli.netlify.app/atlas-cli-changelog/#atlas-cli-1.27.1)

### CODE REVIEW

**Comment by jeroenvervaeke** [comment]
Should we include anything about the changes you made @fmenezes ?
- CLOUDP-268554 Update atlas diagnostics command to add more information
- CLOUDP-268554 Fix atlas deployments inspect errors not showing up

Diff Source: https://github.com/mongodb/docs-atlas-cli/pull/643

**Comment by sarahsimpers** [comment]
Another question for @jeroenvervaeke and @fmenezes, I saw in the changes pulled in from the source repo that dataLakesPipelines commands were removed, is there not a deprecation period for those? Should we note that in RNs?

**Comment by fmenezes** [comment]
> Should we include anything about the changes you made @fmenezes ?
> 
> * CLOUDP-268554 Update atlas diagnostics command to add more information
> * CLOUDP-268554 Fix atlas deployments inspect errors not showing up
> 
> Diff Source: #643

No given it is a hidden command

**Comment by fmenezes** [comment]
> Another question for @jeroenvervaeke and @fmenezes, I saw in the changes pulled in from the source repo that dataLakesPipelines commands were removed, is there not a deprecation period for those? Should we note that in RNs?

Deprecated commands are not documented by default but yes we should add a note here is the main doc https://www.mongodb.com/docs/datalake/data-lake-deprecation/

**Review by jeroenvervaeke — APPROVED** [review]

**Review by lmkerbey-mdb — APPROVED** [review]
LGTM.

**Pull request merged**
