### PR TITLE
(DOCSP-23230) Adds package to install Atlas CLI and mongosh together

### PR DESCRIPTION
**Pull request by sarahsimpers**
[Build Link](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62aa253c1e21bf77b1574bfc)
[Jira Ticket Link](https://jira.mongodb.org/browse/DOCSP-23230)
[Staging: Install (Homebrew, Yum and Apt tabs only)](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-23230/install-atlas-cli/)
[Staging: Release notes](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-23230/atlas-cli-changelog/)

This PR also:

- Updates the submodule to v1.1.3 (previous PR to do this was reverted)
- Adds the 1.1.3 release notes

### CODE REVIEW

**Review by fmenezes — APPROVED** [review]
LGTM

**Comment by fmenezes** [comment]
One note is in homebrew by running `brew install mongodb-atlas` or `brew install mongodb-atlas-cli` we get the same result mongosh is always installed, do you want to also document that here?

**Comment by sarahsimpers** [comment]
> One note is in homebrew by running `brew install mongodb-atlas` or `brew install mongodb-atlas-cli` we get the same result mongosh is always installed, do you want to also document that here?

Sure, I will add that. Thanks!

**Review by melissamahoney-mongodb — APPROVED** [review]
One thought, up to you. Otherwise LGTM.

**Pull request merged**
